services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: 'wordle_postgres'
    environment:
      - 'POSTGRES_DB=${DATABASE_NAME}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${DATABASE_USER}'
    ports:
      - '${DATABASE_PORT}:5432'
